name: data uploader

on:
  workflow_dispatch:
  # schedule:
  #   # 15分ごとに試す
  #   - cron:  '*/15 * * * *'

env:
    MAIN_BRANCH: main
    DEVELOPMENT_BRANCH: development

# データの生成
jobs:
  data_generate:
    runs-on: ubuntu-latest
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
        with:
          repository: hrsano645/covid19-gen-datajson-shizuokapref
          ref: master
#           token: ${{ secrets.DATA_UPLOAD_PAT }}
#           persist-credentials: false
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check pwd ls
        run: ls -la
      - name: Generate data.json
        run:  bash bat.sh
      - name: Upload data.json
        uses: actions/upload-artifact@v1
        with:
          name: datajson
          path: data.json
  data_upload_development:
    needs: data_generate
    runs-on: ubuntu-latest
    steps:
      - name: check env
        run: echo ${{ env.DEVELOPMENT_BRANCH }}
      - uses: actions/checkout@v1
        with:
          ref: ${{ env.DEVELOPMENT_BRANCH }}
#           token: ${{ secrets.DATA_UPLOAD_PAT }}
#           persist-credentials: false
      - name: Download data
        uses: actions/download-artifact@v1
        with:
          name: datajson
      - name: recode commit time
        run: echo `date` > data/auto_generate_time
      - name: Commit files
        run: |
          cp -rp datajson/* data/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git commit -m "Auto Update Data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DATA_UPLOAD_PAT }}
          branch: ${{ env.DEVELOPMENT_BRANCH }}
#   data_upload_deploy:
#     needs: data_upload_development
#     runs-on: ubuntu-latest
#     steps:
#       - name: check env
#         run: echo ${{ env.DEVELOPMENT_BRANCH }}
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ env.MAIN_BRANCH }}
#       - name: Download data
#         uses: actions/download-artifact@v1
#         with:
#           name: datajson
#       - name: recode commit time
#         run: echo `date` > data/auto_generate_time
#       - name: Commit files
#         run: |
#           cp -rp datajson/* data/
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add data/*
#           git commit -m "Auto Update Data"
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ env.MAIN_BRANCH }}
