name: push event

on:
  push:
    branches:
      - development
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: push_nortify
        run: echo "pushed another workflow"
